cairo-contracts/src/apps/transfer/component.cairo
cairo-contracts/src/apps/transfer/types.cairo
cairo-contracts/src/clients.cairo
cairo-contracts/src/clients/tendermint.cairo
cairo-contracts/src/clients/tendermint/client_state.cairo
cairo-contracts/src/clients/tendermint/component.cairo
cairo-contracts/src/clients/tendermint/consensus_state.cairo
cairo-contracts/src/clients/tendermint/errors.cairo
cairo-contracts/src/clients/tendermint/header.cairo
cairo-contracts/src/core/channel/types.cairo
cairo-contracts/src/core/client.cairo
cairo-contracts/src/core/client/component.cairo
cairo-contracts/src/core/client/contract.cairo
cairo-contracts/src/core/client/errors.cairo
cairo-contracts/src/core/client/interface.cairo
cairo-contracts/src/core/client/msgs.cairo
cairo-contracts/src/core/client/types.cairo
cairo-contracts/src/core/host.cairo
cairo-contracts/src/core/host/types.cairo
cairo-contracts/src/lib.cairo
cairo-contracts/src/presets.cairo
cairo-contracts/src/presets/ibc.cairo
cairo-contracts/src/tests/config.cairo
cairo-contracts/src/tests/mocks/transfer_mock.cairo

Part of #20
This PR establishes the core types, interfaces, and implementations needed to draw the relationship between the ICS-02 client component and each distinct client type (here ICS-07). The ICS02 component acts as a client router, responsible for processing messages like `MsgCreateClient`, `MsgUpdateClient`, `MsgRecoverClient`, and `MsgUpgradeClient`. Upon receiving one of these messages, it routes the message to the appropriate Cairo contract for the specified client.
As for the architecture, briefly: each client type should have its own Cairo contract, which can be declared and deployed by anyone. However, the light client's `ContractAddress` must be registered with the IBC core contract, a process only the governance contract is authorized to perform. Once registered, the …

feat: establish ICS02 and ICS07 components + implement client creation and update logic

---

cairo-contracts/packages/apps/src/transfer/components/transfer.cairo
cairo-contracts/packages/apps/src/transfer/interfaces.cairo
cairo-contracts/packages/apps/src/transfer/interfaces/transfer.cairo
cairo-contracts/packages/contracts/src/apps/transfer.cairo
cairo-contracts/packages/contracts/src/tests/mocks/transfer_mock.cairo
cairo-contracts/packages/contracts/src/tests/setups/transfer.cairo
cairo-contracts/packages/contracts/src/tests/test_transfer.cairo
cairo-contracts/packages/core/src/channel/interface.cairo
relayer/crates/starknet-integration-tests/tests/ibc.rs

In this PR, the `IRecvPacket` interface under ICS-20 has been removed. Now, packet processing will only occur when a packet is passed to the ICS-20 contract via application callbacks (methods under the `IAppCallback`).
Additionally, the methods under `ISendTransfer` have been merged, and we will now expose a single `send_transfer` entry point. (cc @soareschen) This change aims for improved contract security by reducing unnecessary exposure.

imp: refine ICS20 and `IAppCallback` interfaces and improve the wiring

---

light-client/Cargo.lock
relayer/Cargo.lock
relayer/Cargo.toml
relayer/crates/starknet-chain-components/src/impls/queries/status.rs
relayer/crates/starknet-integration-tests/Cargo.toml
relayer/crates/starknet-integration-tests/tests/light_client.rs

This PR adds some tests for performing one-sided handshake with the Wasm light client on Cosmos, without actually relaying anything to Starknet. We simply submit dummy proofs to the Cosmos chain, which the light client currently always validate successfully.

Test performing dummy IBC handshake with Wasm Starknet light client on Cosmos

---

cairo-contracts/packages/apps/Scarb.toml
cairo-contracts/packages/apps/src/tests/config.cairo
cairo-contracts/packages/apps/src/transfer/components/transfer.cairo
cairo-contracts/packages/clients/src/cometbft/component.cairo
cairo-contracts/packages/clients/src/cometbft/consensus_state.cairo
cairo-contracts/packages/clients/src/cometbft/header.cairo
cairo-contracts/packages/clients/src/tests/config.cairo
cairo-contracts/packages/contracts/src/tests/test_transfer.cairo
cairo-contracts/packages/core/src/channel/channel_call.cairo
cairo-contracts/packages/core/src/channel/components/handler.cairo
cairo-contracts/packages/core/src/channel/errors.cairo
cairo-contracts/packages/core/src/channel/interface.cairo
cairo-contracts/packages/core/src/channel/types.cairo
cairo-contracts/packages/core/src/client/client_call.cairo
cairo-contracts/packages/core/src/client/interface.cairo
cairo-contracts/packages/core/src/client/types.cairo
cairo-contracts/packages/core/src/host/errors.cairo
cairo-contracts/packages/core/src/host/identifiers.cairo
cairo-contracts/packages/core/src/host/keys.cairo
cairo-contracts/packages/core/src/host/prefixes.cairo
cairo-contracts/packages/core/src/lib.cairo
cairo-contracts/packages/core/src/router/app_call.cairo
cairo-contracts/packages/core/src/tests/dummy.cairo
cairo-contracts/packages/core/src/tests/test_channel.cairo

feat: add `send_packet` handler and connect IBC core to ICS20 contract

---

cairo-contracts/Scarb.lock
cairo-contracts/Scarb.toml
cairo-contracts/packages/clients/Scarb.toml
cairo-contracts/packages/clients/src/cometbft/component.cairo
cairo-contracts/packages/clients/src/cometbft/errors.cairo
cairo-contracts/packages/clients/src/tests/cometbft.cairo
cairo-contracts/packages/core/src/client/interface.cairo
cairo-contracts/packages/core/src/client/types.cairo
cairo-contracts/packages/core/src/commitment/types.cairo
cairo-contracts/packages/core/src/lib.cairo

Requested by @soareschen 
> We need a query method from the client contract for [finding the consensus state height](https://github.com/informalsystems/hermes-sdk/blob/main/crates/chain/chain-components/src/traits/queries/consensus_state_height.rs#L24-L28) before a given target height.
This is needed to determine which trusted height to be used on the Cosmos chain to build the UpdateClient header. In the Cosmos chain implementation, we had to get a list of all consensus heights and then sort and find the trusted height, which is not very efficient. It would be good if there are ways to implement this more efficiently on the chain side.
This PR introduces the `update_height_before` method to the `IClientQuery` interface, and make the comet client to keep track of the heights at which a …

feat: add endpoint to query latest updated height at or below target height

---

relayer/crates/starknet-chain-components/src/impls/contract/message.rs
relayer/crates/starknet-chain-components/src/impls/counterparty_message_height.rs
relayer/crates/starknet-chain-components/src/impls/messages/channel.rs
relayer/crates/starknet-chain-components/src/impls/messages/connection.rs
relayer/crates/starknet-chain-components/src/impls/messages/create_client.rs
relayer/crates/starknet-chain-components/src/impls/messages/update_client.rs
relayer/crates/starknet-chain-components/src/impls/send_message.rs
relayer/crates/starknet-chain-components/src/impls/types/message.rs
relayer/crates/starknet-chain-components/src/types/messages/erc20/transfer.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs
relayer/crates/starknet-integration-tests/src/tests/light_client.rs
relayer/crates/starknet-integration-tests/src/tests/update_clients.rs

Closes: #141
This PR adds a `StarknetMessage` which contains the counterparty Cosmos height and uses this type instead of `Call` for messages

Introduce `StarknetMessage` type containing counterparty Cosmos height

---

cairo-contracts/packages/apps/src/transfer/components/transfer.cairo
cairo-contracts/packages/apps/src/transfer/interfaces/transfer.cairo
cairo-contracts/packages/core/src/channel/types.cairo
flake.lock
flake.nix
relayer/Cargo.lock
relayer/crates/cairo-encoding-components/src/components/encode_mut.rs
relayer/crates/starknet-chain-components/Cargo.toml
relayer/crates/starknet-chain-components/src/components/chain.rs
relayer/crates/starknet-chain-components/src/components/encoding/cairo.rs
relayer/crates/starknet-chain-components/src/impls/events/ack.rs
relayer/crates/starknet-chain-components/src/impls/messages/packet.rs
relayer/crates/starknet-chain-components/src/impls/queries/packet_receipt.rs
relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/channel_message.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/denom.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/ibc_transfer.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/packet.rs
relayer/crates/starknet-chain-context/src/contexts/chain.rs
relayer/crates/starknet-chain-context/src/contexts/encoding/cairo.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

Partially resolves #170 #171
ics20 transfer: cosmos -> starknet -> cosmos

feat(e2e): native token transfer from cosmos to starknet

---

relayer/crates/starknet-chain-components/src/impls/messages/packet.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

Closes #170
Closes #171
ics20 transfer: starknet -> cosmos -> starknet

feat(e2e): transfer erc20 token from starknet to cosmos and back

---

cairo-contracts/packages/core/src/channel/components/handler.cairo
cairo-contracts/packages/core/src/channel/errors.cairo
cairo-contracts/packages/core/src/channel/interface.cairo

Closes: #219
This PR introduces two new methods, `unreceived_packet_sequences` and `unreceived_ack_sequences` to the `IChannelQuery` interface. These methods filter pending packets based on a provided list of sequences. 
If an empty array of sequences is passed, the methods throw an error. This behavior differs from the typical implementation in Cosmos chains, where passing an empty array would return all unreceived packets. The decision to deviate from this convention is intentional. Otherwise it requires the Cairo contract to maintain and update a list of received commitment and acknowledgment keys (computed from paths using Poseidon hashing), where the size of list only can be up to the 255 elements. This also would necessitate to deal with deletion upon packet processing completion, …

feat: implement query methods for unreceived packets and acks

---

flake.nix
light-client/Cargo.lock
light-client/Cargo.toml
nix/ibc-starknet-cw.nix
relayer/Cargo.lock
relayer/Cargo.toml

closes #233
patch at ibc-rs: https://github.com/cosmos/ibc-rs/compare/rano/empty-rev-number-in-height

fix(lc/starknet): use `ibc-rs` patch for empty `revision_number` in `ibc-go-wasm-v8`

---

relayer/crates/starknet-integration-tests/src/tests/ics20.rs

Closes #237
successful ics20 test with `osmosisd` binary as cosmos node.

feat: `osmosisd` on ics20 e2e test

---

relayer/Cargo.lock
relayer/Cargo.toml
relayer/crates/starknet-chain-components/src/components/chain.rs
relayer/crates/starknet-chain-components/src/impls/messages/ibc_transfer.rs
relayer/crates/starknet-chain-components/src/impls/messages/mod.rs
relayer/crates/starknet-chain-components/src/impls/send_message.rs
relayer/crates/starknet-chain-context/src/contexts/chain.rs
relayer/crates/starknet-chain-context/src/impls/error.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

This PR modifies the ICS20 test to run with a background relayer that relay packets through event subscription. We also modify the test to use a separate user wallet on Starknet to perform token transfer, to avoid nonce conflict when the relayer relays the packet.
A stubbed implementation of `IbcTokenTransferMessageBuilder` is added, but we cannot implement it yet, due to some mismatch in the transfer API offered by the ICS20 Cairo contract.

Run background relayer in test

---

relayer/crates/starknet-chain-components/src/components/encoding/cairo.rs
relayer/crates/starknet-chain-components/src/impls/events/ack.rs
relayer/crates/starknet-chain-components/src/impls/events/send_packet.rs
relayer/crates/starknet-chain-components/src/impls/messages/channel.rs
relayer/crates/starknet-chain-components/src/impls/messages/connection.rs
relayer/crates/starknet-chain-components/src/impls/packet_fields.rs
relayer/crates/starknet-chain-components/src/impls/queries/ack_commitment.rs
relayer/crates/starknet-chain-components/src/impls/queries/channel_end.rs
relayer/crates/starknet-chain-components/src/impls/queries/client_state.rs
relayer/crates/starknet-chain-components/src/impls/queries/consensus_state.rs
relayer/crates/starknet-chain-components/src/impls/queries/counterparty_chain_id.rs
relayer/crates/starknet-chain-components/src/impls/queries/packet_commitment.rs
relayer/crates/starknet-chain-components/src/impls/queries/packet_receipt.rs
relayer/crates/starknet-chain-components/src/impls/queries/packet_received.rs
relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/channel_message.rs
relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/packet_fields.rs
relayer/crates/starknet-chain-components/src/types/channel_id.rs
relayer/crates/starknet-chain-components/src/types/client_id.rs
relayer/crates/starknet-chain-components/src/types/connection_id.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/channel.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/connection.rs
relayer/crates/starknet-chain-components/src/types/mod.rs
relayer/crates/starknet-chain-components/src/types/utils.rs
relayer/crates/starknet-chain-context/src/contexts/encoding/cairo.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs
relayer/crates/starknet-integration-tests/src/tests/light_client.rs

Use `ConnectionEnd` and `ChannelEnd` from `ibc-rs` and all other dependent types.
I am rexporting `ibc-rs` types as Starknet/Cairo types to avoid too many changes in the imports. So, you see `StarknetChannelId` and `IbcChannelId` (as similar) at some places. These are actually the same types. 
linked to #150

feat(relayer): reuse `ConnectionEnd` and `ChannelEnd` from `ibc-rs`

---

cairo-contracts/packages/apps/src/transfer/components/transfer.cairo
cairo-contracts/packages/contracts/src/tests/channel.cairo
cairo-contracts/packages/contracts/src/tests/client.cairo
cairo-contracts/packages/core/src/channel/components/handler.cairo
cairo-contracts/packages/core/src/client/components/handler.cairo
cairo-contracts/packages/testkit/src/setup.cairo

feat: only authorized relayers can invoke handlers with commitment proof verification

---

relayer/crates/starknet-chain-components/src/impls/events/send_packet.rs
relayer/crates/starknet-chain-components/src/impls/packet_fields.rs
relayer/crates/starknet-chain-components/src/impls/payload_builders/create_client.rs
relayer/crates/starknet-chain-components/src/impls/payload_builders/update_client.rs
relayer/crates/starknet-chain-components/src/impls/queries/client_state.rs
relayer/crates/starknet-chain-components/src/impls/queries/consensus_state.rs
relayer/crates/starknet-chain-components/src/impls/queries/status.rs
relayer/crates/starknet-chain-components/src/types/client_id.rs
relayer/crates/starknet-chain-components/src/types/cosmos/timestamp.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

fix(relayer): use starknet block timestamp

---

.github/workflows/hermes.yaml
light-client/ibc-client-starknet/src/client_state/cw.rs
light-client/ibc-client-starknet/src/client_state/execution.rs
relayer/crates/starknet-chain-components/src/impls/payload_builders/create_client.rs
relayer/crates/starknet-integration-tests/src/tests/light_client.rs

fix(lc/starknet): incorrect height during client and consensus state updates

---

cairo-contracts/packages/apps/src/tests/transfer.cairo
cairo-contracts/packages/contracts/src/tests/channel.cairo
cairo-contracts/packages/core/src/channel/components/handler.cairo
cairo-contracts/packages/testkit/src/configs/core.cairo
cairo-contracts/packages/testkit/src/configs/transfer.cairo

fix: use correct port and channel IDs during channel end retrieval in `ack_packet`

---

.env.example
.github/workflows/cairo.yaml
.github/workflows/hermes.yaml
cairo-contracts/.tool-versions
cairo-contracts/README.md
cairo-contracts/Scarb.lock
cairo-contracts/Scarb.toml
cairo-contracts/packages/apps/Scarb.toml
cairo-contracts/packages/clients/Scarb.toml
cairo-contracts/packages/core/Scarb.toml
cairo-contracts/packages/testkit/Scarb.toml
cairo-libs/.tool-versions
cairo-libs/Scarb.lock
cairo-libs/Scarb.toml
cairo-libs/packages/cometbft/Scarb.toml
cairo-libs/packages/protobuf/Scarb.toml
flake.lock
flake.nix
nix/cairo.nix
nix/scarb.nix
nix/starknet-foundry.nix
relayer/Cargo.toml

required for #177. we need [`LowerHex`](https://github.com/starkware-libs/cairo/blob/3c5a2f414204388da4db6f9530cd22e6d1ba5184/corelib/src/fmt.cairo#L336) which is introduced in cairo 2.9.0.
- updated:
- scarb 2.9.2
- cairo 2.9.2
- starknet 2.9.2
- openzeppelin 0.20.0
- snforge 0.34.0
- alexandria rev-162bed1
- faster cairo CI jobs.

build(cairo): update scarb to 2.9.2

---

cairo-contracts/packages/apps/src/tests/transfer.cairo
cairo-contracts/packages/apps/src/transfer/components/transfer.cairo
cairo-contracts/packages/contracts/src/tests/transfer.cairo
relayer/crates/starknet-integration-tests/src/tests/clear_packets.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

In continuation of #275
Closes: #276

refactor: transfer to ICS20 first then burn

---

.github/workflows/hermes.yaml
relayer/Cargo.lock

Closes: #261
This PR updates Hermes SDK to commit https://github.com/informalsystems/hermes-sdk/commit/b7735c878d9527f2219d64320bf44f94a4a572d2 which adds logs for client update and sets logs when relaying receive, timeout and ack packets from `trace` to `debug`

build(deps): update Hermes SDK

---

relayer/crates/starknet-integration-tests/src/tests/clear_packets.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

This PR map the `execution.send()` error to be display as Debug in tests
Old error:
```
Error: TransactionExecutionError
```
New error:
```
Error: StarknetError: TransactionExecutionError(TransactionExecutionErrorData { transaction_index: 0, execution_error:
"Transaction execution has failed:\n0: Error in the called contract (contract address:
0x049dfb8ce986e21d354ac93ea65e6a11f639c1934ea253e5ff14ca62eca0f38e, class hash:
0x061dac032f228abef9c6626f995015233097ae253a7f72d68552db02f2971b8f, selector:
0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):\nError at pc=0:4835:\nCairo
traceback (most recent call last):\nUnknown location (pc=0:67)\nUnknown location (pc=0:1835)\nUnknown location
(pc=0:2554)\nUnknown location (pc=0:3436)\nUnknown location (pc=0:4040)\n\n1: Error in …
```

Improve test error log

---

relayer/crates/starknet-chain-components/src/impls/contract/call.rs
relayer/crates/starknet-chain-components/src/impls/contract/declare.rs

fix: use `BlockTag::Latest` when querying Starknet

---

relayer/crates/starknet-chain-components/src/impls/types/address.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

Fixes the issue discussed in #313.
This PR uses the new `create_ibc_token` Cairo contract call introduced in #321 to pre-allocate the token address for tokens transferred from Cosmos to Starknet. This allows us to use the `assert_eventual_amount` method to poll for the transfer status, since we can now know the transferred address beforehand.

fix: pre-create IBC token in test to reduce flakiness

---

cairo-contracts/packages/apps/src/tests/transfer.cairo
cairo-contracts/packages/apps/src/transfer/components/transfer.cairo
cairo-contracts/packages/apps/src/transfer/erc20_call.cairo
cairo-contracts/packages/apps/src/transfer/errors.cairo
cairo-contracts/packages/apps/src/transfer/interfaces/transfer.cairo
cairo-contracts/packages/apps/src/transfer/types.cairo
cairo-contracts/packages/contracts/src/tests/transfer.cairo
cairo-contracts/packages/testkit/src/handles/app.cairo
relayer/crates/starknet-chain-components/src/types/messages/ibc/denom.rs
relayer/crates/starknet-integration-tests/src/tests/ics20.rs

Completes #321
- Checks if channel end exists and is open
- Works with multihop scenarios

fix: ensure adequate checks and tests for `create_ibc_token`

---

cairo-contracts/packages/core/src/channel/components/events.cairo
cairo-contracts/packages/core/src/commitment/types.cairo
cairo-contracts/packages/core/src/tests/commitment.cairo
relayer/Cargo.lock
relayer/crates/starknet-chain-components/Cargo.toml
relayer/crates/starknet-chain-components/src/components/chain.rs
relayer/crates/starknet-chain-components/src/impls/events/ack.rs
relayer/crates/starknet-chain-components/src/impls/messages/ibc_transfer.rs
relayer/crates/starknet-chain-components/src/impls/messages/packet.rs
relayer/crates/starknet-chain-components/src/impls/queries/ack_commitment.rs
relayer/crates/starknet-chain-components/src/impls/queries/nonce.rs
relayer/crates/starknet-chain-components/src/impls/send_message.rs
relayer/crates/starknet-chain-components/src/impls/transfer.rs
relayer/crates/starknet-chain-components/src/impls/types/config.rs
relayer/crates/starknet-chain-components/src/impls/types/signer.rs
relayer/crates/starknet-chain-components/src/impls/types/wallet.rs
relayer/crates/starknet-chain-components/src/traits/account.rs
relayer/crates/starknet-chain-components/src/traits/mod.rs
relayer/crates/starknet-chain-components/src/traits/signer.rs
relayer/crates/starknet-chain-components/src/types/cosmos/timestamp.rs
relayer/crates/starknet-chain-components/src/types/events/packet.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/denom.rs
relayer/crates/starknet-chain-components/src/types/messages/ibc/packet.rs
relayer/crates/starknet-chain-context/src/contexts/chain.rs
relayer/crates/starknet-chain-context/src/impls/error.rs
relayer/crates/starknet-cli/src/contexts/app.rs
relayer/crates/starknet-integration-tests/src/contexts/bootstrap.rs
relayer/crates/starknet-integration-tests/src/tests/clear_packets.rs
relayer/crates/starknet-relayer/src/contexts/builder.rs

Closes: #345 #337
This PR has 2 changes on Cairo side:
* Use nanoseconds instead of seconds for timeout timestamps
* Replace the `packet_data` field with `packet` in the `WriteAcknowledgementEvent`
This PR has 2 changes on the relayer side:
* Improve packet clearing test to assert recv and ack are cleared both ways
* Fix `build_packet_from_write_ack_event`

Fix ack clearing from Cosmos to Starknet

---

.github/workflows/hermes.yaml
.github/workflows/light-client.yaml
cairo-contracts/packages/apps/Scarb.toml
cairo-contracts/packages/clients/Scarb.toml
cairo-contracts/packages/testkit/Scarb.toml

fix
- correct rust cache paths
- sequential test runner only for macos-arm64
- getting failure will be faster on linux-amd64 and linux-arm64
- release profile during integration tests for faster runtime 
current bottleneck
- integration tests themselves
- `snforge_scarb_plugin` always gets recompiled by cargo (pulled as `snforge_std` dep)
- opened software-mansion/setup-scarb#37
- nix fetch for necessary tools -- it recursively tries to pull all their dependencies.
- using a rust toolchain action and something like `robinraju/release-downloader@v1` would be faster.
- although we don't have a release binary for simd-ibc-go-v8-wasm - for that we rely on nix

ci: optimize integration test runtime

---

relayer/Cargo.lock
relayer/Cargo.toml
relayer/crates/starknet-cli/Cargo.toml
relayer/crates/starknet-cli/src/commands/all.rs
relayer/crates/starknet-cli/src/commands/start.rs
relayer/crates/starknet-cli/src/contexts/app.rs

Part of: #198
This PR enhances the `start` CLI for `hermes-starknet`, so that the chain ID and client ID parameters are named by the chain type instead of by the position. e.g. `--starknet-chain-id` and `--cosmos-chain-id` are used instead of `--chain-id-a` and `--chain-id-b`.
This is done by defining our own version of `StartRelayerArgs`, which renames the name of the command line arguments. The underlying fields are still named the same, e.g. `--starknet-chain-id` is mapped to `chain_id_a`.
Following this PR, similar pattern can be applied to other CLIs so that we can make the CLI less confusing.

Enhance start CLI to accept parameters by chain type name

---

.github/workflows/hermes.yaml

This PR adds the flag `--success-output=final` to `starknet-integration-tests` and `madara-integration-tests` so that logs are displayed even when tests succeeds in CI

ci: output logs even when tests succeed
