cairo-contracts/packages/apps/src/transfer/components/transfer.cairo, cairo-contracts/packages/clients/src/cometbft/component.cairo, cairo-contracts/packages/clients/src/tests/mocks/mock_cometbft.cairo, cairo-contracts/packages/clients/src/tests/test_cometbft.cairo, cairo-contracts/packages/contracts/src/clients/cometbft.cairo, cairo-contracts/packages/contracts/src/core.cairo, cairo-contracts/packages/contracts/src/tests/handles/core.cairo, cairo-contracts/packages/contracts/src/tests/test_channel.cairo, cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/channel/interface.cairo, cairo-contracts/packages/core/src/client/client_call.cairo, cairo-contracts/packages/core/src/client/components/handler.cairo, cairo-contracts/packages/core/src/client/interface.cairo, cairo-contracts/packages/core/src/lib.cairo, cairo-contracts/packages/core/src/router/component.cairo
=> feat: add dedicated query interfaces to IBC client/channel components

cairo-contracts/packages/apps/src/lib.cairo, cairo-contracts/packages/apps/src/tests/ack.cairo, cairo-contracts/packages/apps/src/tests/transfer.cairo, cairo-contracts/packages/apps/src/transfer/components/transfer.cairo, cairo-contracts/packages/apps/src/transfer/errors.cairo, cairo-contracts/packages/apps/src/transfer/types.cairo, cairo-contracts/packages/clients/src/cometbft/component.cairo, cairo-contracts/packages/contracts/src/tests/channel.cairo, cairo-contracts/packages/core/src/channel/components/events.cairo, cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/channel/errors.cairo, cairo-contracts/packages/core/src/channel/interface.cairo, cairo-contracts/packages/core/src/channel/msgs.cairo, cairo-contracts/packages/core/src/channel/types.cairo, cairo-contracts/packages/core/src/client/client_call.cairo, cairo-contracts/packages/core/src/client/interface.cairo, cairo-contracts/packages/core/src/client/types.cairo, cairo-contracts/packages/core/src/host/keys.cairo, cairo-contracts/packages/core/src/host/prefixes.cairo, cairo-contracts/packages/core/src/lib.cairo, cairo-contracts/packages/core/src/router/app_call.cairo, cairo-contracts/packages/core/src/router/component.cairo, cairo-contracts/packages/testkit/src/configs/transfer.cairo, cairo-contracts/packages/testkit/src/event_spy/channel.cairo, cairo-contracts/packages/testkit/src/event_spy/transfer.cairo, cairo-contracts/packages/testkit/src/handles/app.cairo, cairo-contracts/packages/testkit/src/handles/core.cairo, cairo-contracts/packages/testkit/src/lib.cairo, cairo-contracts/packages/testkit/src/setup.cairo
This PR includes:
- Implementation of the `ack_packet` handler in the channel component
- Addition of the `on_ack_packet` callback in the ICS-20 component
- Tests for ack packet submission, covering both ack failure(refund) and success scenarios
- Unit tests to verify acknowledgment equality checks
- Improved organization of callback implementations in the ICS-20 component
=> feat: implement packet acknowledgement handler + tests

light-client/Cargo.lock, relayer/Cargo.lock, relayer/Cargo.toml, relayer/crates/starknet-chain-components/Cargo.toml, relayer/crates/starknet-chain-components/src/components/chain.rs, relayer/crates/starknet-chain-components/src/components/starknet_to_cosmos.rs, relayer/crates/starknet-chain-components/src/impls/events/create_client.rs, relayer/crates/starknet-chain-components/src/impls/events/mod.rs, relayer/crates/starknet-chain-components/src/impls/messages/mod.rs, relayer/crates/starknet-chain-components/src/impls/messages/update_client.rs, relayer/crates/starknet-chain-components/src/impls/mod.rs, relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/mod.rs, relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/update_client_payload.rs, relayer/crates/starknet-chain-components/src/types/cosmos/client_state.rs, relayer/crates/starknet-chain-components/src/types/cosmos/update.rs, relayer/crates/starknet-chain-context/src/contexts/chain.rs, relayer/crates/starknet-integration-tests/src/tests/ibc_client.rs, relayer/crates/starknet-relayer/src/contexts/starknet_to_cosmos_relay.rs
Related: https://github.com/informalsystems/hermes-sdk/pull/468
=> Implement UpdateClient chain methods from Cosmos to Starknet

justfile, relayer/Cargo.lock, relayer/Cargo.toml, relayer/crates/starknet-integration-tests/Cargo.toml, relayer/crates/starknet-integration-tests/src/tests/light_client.rs
```bash
nix develop
just build-cw-contract
cd relayer
export STARKNET_WASM_CLIENT_PATH=../../../light-client/target/wasm32-unknown-unknown/release/ibc_client_starknet_cw.wasm
cargo test test_starknet_light_client -- --no-capture
```
=> feat: upload gzipped wasm blob

relayer/crates/starknet-chain-components/src/components/encoding/cairo.rs, relayer/crates/starknet-chain-components/src/components/encoding/event.rs, relayer/crates/starknet-chain-components/src/types/cosmos/mod.rs, relayer/crates/starknet-chain-components/src/types/cosmos/timestamp.rs, relayer/crates/starknet-chain-components/src/types/events/ics20.rs, relayer/crates/starknet-chain-components/src/types/events/mod.rs, relayer/crates/starknet-chain-components/src/types/events/packet.rs, relayer/crates/starknet-chain-components/src/types/messages/ibc/packet.rs, relayer/crates/starknet-chain-context/src/contexts/encoding/event.rs, relayer/crates/starknet-integration-tests/src/tests/ics20.rs
Packet msgs:
- Ack
- Timeout
Packet events:
- Send
- Receive
- WriteAck
- Ack
- Timeout
ICS20 events:
- Send
- Ack
- AckStatus
- Timeout
=> feat(relayer): packet and ics20 messages and events

relayer/crates/starknet-chain-components/src/components/encoding/cairo.rs, relayer/crates/starknet-chain-components/src/components/types.rs, relayer/crates/starknet-chain-components/src/impls/queries/connection_end.rs, relayer/crates/starknet-chain-components/src/types/connection_id.rs, relayer/crates/starknet-chain-context/src/contexts/chain.rs, relayer/crates/starknet-chain-context/src/contexts/encoding/cairo.rs
=> feat(relayer): `ConnectionEndWithProofsQuerier` and `ConnectionEndQuerier`

relayer/crates/starknet-cli/src/commands/query/subcommand.rs, relayer/crates/starknet-cli/src/contexts/app.rs, relayer/crates/starknet-cli/src/impls/error.rs
This PR adds the `query consensus-state` CLI from Starknet to Cosmos
=> Add query consensus-state CLI

relayer/crates/starknet-chain-components/src/impls/messages/connection.rs, relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/connection_message.rs, relayer/crates/starknet-chain-components/src/types/client_id.rs
=> feat(hermes-sdk): build connection handshake messages

relayer/crates/starknet-chain-components/src/components/encoding/cairo.rs, relayer/crates/starknet-chain-components/src/components/types.rs, relayer/crates/starknet-chain-components/src/impls/queries/channel_end.rs, relayer/crates/starknet-chain-components/src/types/channel_end.rs, relayer/crates/starknet-chain-components/src/types/channel_id.rs, relayer/crates/starknet-chain-components/src/types/mod.rs, relayer/crates/starknet-chain-context/src/contexts/chain.rs, relayer/crates/starknet-chain-context/src/contexts/encoding/cairo.rs
=> feat(hermes-sdk): query starknet for channel end

relayer/Cargo.lock, relayer/crates/starknet-chain-components/src/types/status.rs, relayer/crates/starknet-cli/src/commands/query/subcommand.rs, relayer/crates/starknet-cli/src/contexts/app.rs
This PR adds the `query chain-status` CLI
=> Add `query chain-status` CLI

relayer/crates/starknet-chain-components/src/impls/messages/channel.rs, relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/channel_message.rs, relayer/crates/starknet-chain-context/src/contexts/chain.rs
=> feat(hermes-sdk): build channel handshake messages

cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/channel/interface.cairo, cairo-contracts/packages/testkit/src/handles/core.cairo
=> feat(cairo): return `ChannelId` from chan open init and try handler

cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/channel/interface.cairo, cairo-contracts/packages/core/src/commitment/types.cairo, cairo-contracts/packages/core/src/lib.cairo, cairo-contracts/packages/testkit/src/dummies/transfer.cairo, relayer/crates/cairo-encoding-components/src/components/encode_mut.rs, relayer/crates/starknet-chain-components/src/impls/events/ack.rs, relayer/crates/starknet-chain-components/src/impls/messages/packet.rs, relayer/crates/starknet-chain-components/src/impls/queries/ack_commitment.rs, relayer/crates/starknet-chain-components/src/impls/queries/packet_commitment.rs, relayer/crates/starknet-chain-components/src/impls/queries/packet_receipt.rs, relayer/crates/starknet-chain-components/src/impls/queries/packet_received.rs, relayer/crates/starknet-chain-components/src/types/messages/ibc/packet.rs, relayer/crates/starknet-chain-context/src/contexts/chain.rs
=> feat(relayer): build packet messages, query packet status, extract packet event

cairo-contracts/packages/apps/src/lib.cairo, cairo-contracts/packages/utils/src/utils.cairo
Caught here: https://github.com/informalsystems/ibc-starknet/pull/186#discussion_r1913311443
=> fix(contract): unnecessary double hashing in keys

light-client/Cargo.lock, light-client/ibc-client-starknet-types/src/encoding/components.rs, light-client/ibc-client-starknet-types/src/encoding/impls/header.rs, light-client/ibc-client-starknet-types/src/header.rs, light-client/ibc-client-starknet/src/client_state/execution.rs, light-client/ibc-client-starknet/src/encoding/context.rs, relayer/crates/starknet-chain-components/src/components/encoding/protobuf.rs, relayer/crates/starknet-chain-components/src/impls/starknet_to_cosmos/update_client_message.rs, relayer/crates/starknet-chain-context/src/contexts/encoding/protobuf.rs
=> Add trusted relayer verification on Cosmos side

.github/workflows/hermes.yaml, flake.lock, flake.nix
=> build(nix): fix osmosis fetch via http

cairo-contracts/Scarb.lock, cairo-contracts/packages/core/Scarb.toml, cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/channel/interface.cairo, cairo-contracts/packages/core/src/host/identifiers.cairo, cairo-contracts/packages/core/src/tests/channel.cairo
=> feat: implement query send/ack packet sequences endpoints

cairo-contracts/packages/clients/src/cometbft/component.cairo, cairo-contracts/packages/clients/src/tests/cometbft.cairo
=> fix: use header height when updating clients with older headers

cairo-contracts/packages/apps/src/tests/transfer.cairo, cairo-contracts/packages/apps/src/transfer/components/transfer.cairo, cairo-contracts/packages/contracts/src/tests/transfer.cairo, cairo-contracts/packages/testkit/src/event_spy/erc20.cairo, cairo-contracts/packages/testkit/src/lib.cairo
=> imp: mint to ICS20 first then transfer to user

relayer/crates/starknet-chain-components/src/impls/types/config.rs, relayer/crates/starknet-cli/src/contexts/app.rs, relayer/crates/starknet-relayer/src/contexts/builder.rs
=> refactor: use `Url` for `json_rpc_url`

cairo-contracts/packages/contracts/src/tests/channel.cairo, cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/channel/interface.cairo, cairo-contracts/packages/core/src/tests/channel.cairo, cairo-contracts/packages/testkit/src/handles/core.cairo, relayer/Cargo.lock, relayer/Cargo.toml, relayer/crates/starknet-chain-components/src/impls/queries/packet_commitment.rs
Closes: #291
Depends on https://github.com/informalsystems/hermes-sdk/pull/543
=> refactor: return `None` if packet commitment not found in queries

relayer/Cargo.lock, relayer/Cargo.toml, relayer/crates/starknet-chain-components/Cargo.toml, relayer/crates/starknet-chain-components/src/components/chain.rs, relayer/crates/starknet-chain-components/src/impls/tx_response.rs, relayer/crates/starknet-chain-components/src/impls/types/config.rs, relayer/crates/starknet-chain-context/Cargo.toml, relayer/crates/starknet-chain-context/src/contexts/chain.rs, relayer/crates/starknet-cli/src/contexts/app.rs, relayer/crates/starknet-integration-tests/src/contexts/bootstrap.rs, relayer/crates/starknet-relayer/src/contexts/builder.rs
Closes: #290
This PR adds a new configuration for Starknet chains which sets the polling interval
=> Add `poll_interval` configuration for Starknet chains

relayer/crates/starknet-chain-components/src/impls/types/config.rs, relayer/crates/starknet-cli/src/contexts/app.rs, relayer/crates/starknet-relayer/src/contexts/builder.rs
=> fix: cairo contract information in `StarknetChainConfig`

cairo-contracts/packages/apps/src/lib.cairo, cairo-contracts/packages/apps/src/tests/transfer.cairo, cairo-contracts/packages/apps/src/transfer/components/transfer.cairo, cairo-contracts/packages/apps/src/transfer/interfaces/transfer.cairo, cairo-contracts/packages/contracts/src/apps/transfer.cairo, cairo-contracts/packages/testkit/src/handles/app.cairo, cairo-contracts/packages/testkit/src/mocks/transfer.cairo
=> feat: expose `create_ibc_token` endpoint allowing pre-creation

relayer/Cargo.lock, relayer/crates/starknet-chain-components/src/impls/queries/packet_receipt.rs, relayer/crates/starknet-chain-components/src/impls/types/config.rs, relayer/crates/starknet-chain-context/src/contexts/chain.rs, relayer/crates/starknet-chain-context/src/impls/error.rs, relayer/crates/starknet-cli/src/contexts/app.rs, relayer/crates/starknet-integration-tests/src/contexts/bootstrap.rs, relayer/crates/starknet-relayer/src/contexts/builder.rs, relayer/crates/starknet-relayer/src/contexts/cosmos_starknet_birelay.rs, relayer/crates/starknet-relayer/src/contexts/starknet_cosmos_birelay.rs
Include the following changes:
- https://github.com/informalsystems/hermes-sdk/pull/557
- https://github.com/informalsystems/hermes-sdk/pull/555
- https://github.com/informalsystems/hermes-sdk/pull/554
=> Update Hermes SDK

cairo-contracts/packages/apps/src/tests/transfer.cairo, cairo-contracts/packages/apps/src/transfer/components/transfer.cairo, cairo-contracts/packages/apps/src/transfer/errors.cairo, cairo-contracts/packages/apps/src/transfer/interfaces/transfer.cairo
=> feat: expose `ibc_token_denom` query endpoint

README.md, scripts/deploy.sh
Closes #222
Rendered: https://github.com/informalsystems/ibc-starknet/blob/rano/doc-demo2/README.md
- end user instructions to transfer tokens over IBC with `osmosisd` and `starkli`.
- relayer operator instructions with `hermes-starknet`.
- developer instructions to declare/deploy the contracts and create an IBC channel.
=> docs: update README with instructions 

cairo-libs/packages/cometbft/src/types.cairo
=> refactor: re-define `cometbft::PublicKey` with `Oneof` field

.github/workflows/hermes.yaml, .github/workflows/light-client.yaml, relayer/crates/starknet-chain-components/src/components/chain.rs, relayer/crates/starknet-chain-components/src/impls/assert/assert_duration.rs, relayer/crates/starknet-chain-components/src/impls/assert/mod.rs, relayer/crates/starknet-chain-components/src/impls/mod.rs
=> fix: increase ibc transfer timestamp timeout

cairo-libs/packages/cometbft/src/types.cairo
=> fix: validator ID must be derived from its pub_key

cairo-contracts/Scarb.lock, cairo-contracts/packages/clients/Scarb.toml, cairo-contracts/packages/clients/src/cometbft/component.cairo, cairo-contracts/packages/clients/src/cometbft/errors.cairo, cairo-contracts/packages/clients/src/cometbft/message.cairo, cairo-contracts/packages/clients/src/cometbft/misbehaviour.cairo, cairo-contracts/packages/clients/src/lib.cairo, cairo-contracts/packages/clients/src/mock/component.cairo, cairo-contracts/packages/clients/src/tests/cometbft.cairo, cairo-contracts/packages/contracts/src/tests/client.cairo, cairo-contracts/packages/core/src/client/interface.cairo, cairo-contracts/packages/testkit/src/configs/mock_client.cairo, cairo-contracts/packages/testkit/src/event_spy/client.cairo, cairo-libs/packages/cometbft/src/types.cairo, cairo-libs/packages/cometbft/src/verifier.cairo, cairo-libs/packages/cometbft/tests/verifier.cairo, relayer/crates/starknet-chain-components/src/components/encoding/cairo.rs, relayer/crates/starknet-chain-components/src/impls/messages/update_client.rs, relayer/crates/starknet-chain-components/src/types/cosmos/update.rs
=> feat: cometbft header misbehaviour

light-client/Cargo.lock, light-client/Cargo.toml, nix/ibc-starknet-cw.nix, relayer/Cargo.lock, relayer/Cargo.toml
Update Hermes SDK and CGP with changes from https://github.com/contextgeneric/cgp/pull/88 and https://github.com/informalsystems/hermes-sdk/pull/604
=> Update Hermes SDK and CGP

cairo-contracts/.tool-versions, cairo-contracts/Scarb.lock, cairo-contracts/Scarb.toml, cairo-contracts/packages/apps/src/transfer/components/transfer.cairo, cairo-contracts/packages/clients/src/cometbft/client_state.cairo, cairo-contracts/packages/clients/src/cometbft/component.cairo, cairo-contracts/packages/clients/src/mock/client_state.cairo, cairo-contracts/packages/clients/src/mock/component.cairo, cairo-contracts/packages/core/src/channel/components/handler.cairo, cairo-contracts/packages/core/src/connection/components/handler.cairo, cairo-contracts/packages/core/src/host/identifiers.cairo, cairo-libs/.tool-versions, cairo-libs/Scarb.lock, cairo-libs/Scarb.toml, cairo-libs/packages/cometbft/src/types.cairo, cairo-libs/packages/cometbft/src/verifier.cairo, cairo-libs/packages/ibc_utils/src/storage.cairo, madara-contracts/src/raw.cairo
- snforge to 0.48.0
- openzeppelin_testing to 4.5.0
- removed redundant clone (lints from scarb 2.12.0)
=> build(deps): update `snforge` to `0.48.0`
